export const columnsRequestList = [
  {
    id: "id",
    label: "ID",
    minWidth: 170,
    align: "center",
  },
  {
    id: "requestName",
    label: "Request Name",
    minWidth: 100,
    align: "center",
  },
  {
    id: "status",
    label: "Status",
    minWidth: 170,
    align: "center",
  },
  {
    id: "type",
    label: "Type",
    minWidth: 170,
    align: "center",
  },
  {
    id: "note",
    label: "Note",
    minWidth: 170,
    align: "center",
  },
  {
    id: "pdfFile",
    label: "PDF File",
    minWidth: 170,
    align: "center",
  },
];

export const rowsRequestList = [
  {
    id: 1,
    requestName: "Xác nhận hoãn nghĩa vụ quân sự",
    status: "Waiting",
    type: "PDF",
    note: "NA",
    pdfFile:
      "https://iuoss.com/wp-content/uploads/2022/10/Ho-va-ten-MSSV-XNQS.docx",
  },
  {
    id: 1,
    requestName: "Xác nhận hoãn nghĩa vụ quân sự",
    status: "Waiting",
    type: "Paper",
    note: "NA",
    pdfFile: "",
  },
  {
    id: 1,
    requestName: "Xác nhận hoãn nghĩa vụ quân sự",
    status: "Waiting",
    type: "PDF",
    note: "NA",
    pdfFile:
      "https://iuoss.com/wp-content/uploads/2022/10/Ho-va-ten-MSSV-XNQS.docx",
  },
  {
    id: 1,
    requestName: "Xác nhận hoãn nghĩa vụ quân sự",
    status: "Waiting",
    type: "Paper",
    note: "NA",
    pdfFile: "",
  },
  {
    id: 1,
    requestName: "Xác nhận hoãn nghĩa vụ quân sự",
    status: "Waiting",
    type: "PDF",
    note: "NA",
    pdfFile:
      "https://iuoss.com/wp-content/uploads/2022/10/Ho-va-ten-MSSV-XNQS.docx",
  },
  {
    id: 1,
    requestName: "Xác nhận hoãn nghĩa vụ quân sự",
    status: "Waiting",
    type: "Paper",
    note: "NA",
    pdfFile: "",
  },
  {
    id: 1,
    requestName: "Xác nhận hoãn nghĩa vụ quân sự",
    status: "Waiting",
    type: "Paper",
    note: "NA",
    pdfFile: "",
  },
  {
    id: 1,
    requestName: "Xác nhận hoãn nghĩa vụ quân sự",
    status: "Waiting",
    type: "Paper",
    note: "NA",
    pdfFile: "",
  },
  {
    id: 1,
    requestName: "Xác nhận hoãn nghĩa vụ quân sự",
    status: "Waiting",
    type: "Paper",
    note: "NA",
    pdfFile: "",
  },
  {
    id: 1,
    requestName: "Xác nhận hoãn nghĩa vụ quân sự",
    status: "Waiting",
    type: "Paper",
    note: "NA",
    pdfFile: "",
  },
  {
    id: 1,
    requestName: "Xác nhận hoãn nghĩa vụ quân sự",
    status: "Waiting",
    type: "Paper",
    note: "NA",
    pdfFile: "",
  },
];
export const columnsApprovalList = [
  {
    id: "id",
    label: "ID",
    minWidth: 170,
    align: "center",
  },
  {
    id: "requestName",
    label: "Request Name",
    minWidth: 100,
    align: "center",
  },
  {
    id: "status",
    label: "Status",
    minWidth: 170,
    align: "center",
  },
  {
    id: "type",
    label: "Type",
    minWidth: 170,
    align: "center",
  },
  {
    id: "requestor",
    label: "Requestor",
    minWidth: 170,
    align: "center",
  },
  {
    id: "action",
    label: "Action",
    minWidth: 170,
    align: "center",
  },
];

export const rowsApprovalList = [
  {
    id: 1,
    requestName: "Xác nhận hoãn nghĩa vụ quân sự",
    status: "Waiting",
    type: "PDF",
    requestor: "ITITIU19040",
    action: "",
  },
  {
    id: 1,
    requestName: "Xác nhận hoãn nghĩa vụ quân sự",
    status: "Waiting",
    type: "PDF",
    requestor: "ITITIU19040",
    action: "",
  },
  {
    id: 1,
    requestName: "Xác nhận hoãn nghĩa vụ quân sự",
    status: "Waiting",
    type: "PDF",
    requestor: "ITITIU19040",
    action: "",
  },
  {
    id: 1,
    requestName: "Xác nhận hoãn nghĩa vụ quân sự",
    status: "Waiting",
    type: "PDF",
    requestor: "ITITIU19040",
    action: "",
  },
  {
    id: 1,
    requestName: "Xác nhận hoãn nghĩa vụ quân sự",
    status: "Waiting",
    type: "PDF",
    requestor: "ITITIU19040",
    action: "",
  },
  {
    id: 1,
    requestName: "Xác nhận hoãn nghĩa vụ quân sự",
    status: "Waiting",
    type: "PDF",
    requestor: "ITITIU19040",
    action: "",
  },
  {
    id: 1,
    requestName: "Xác nhận hoãn nghĩa vụ quân sự",
    status: "Waiting",
    type: "PDF",
    requestor: "ITITIU19040",
    action: "",
  },
  {
    id: 1,
    requestName: "Xác nhận hoãn nghĩa vụ quân sự",
    status: "Waiting",
    type: "PDF",
    requestor: "ITITIU19040",
    action: "",
  },
  {
    id: 1,
    requestName: "Xác nhận hoãn nghĩa vụ quân sự",
    status: "Waiting",
    type: "PDF",
    requestor: "ITITIU19040",
    action: "",
  },
  {
    id: 1,
    requestName: "Xác nhận hoãn nghĩa vụ quân sự",
    status: "Waiting",
    type: "PDF",
    requestor: "ITITIU19040",
    action: "",
  },
  {
    id: 1,
    requestName: "Xác nhận hoãn nghĩa vụ quân sự",
    status: "Waiting",
    type: "PDF",
    requestor: "ITITIU19040",
    action: "",
  },
];
