export const columnsRequestList = [
  {
    id: "ticket_id",
    label: "Ticket_id",
    minWidth: 170,
    align: "center",
  },
  {
    id: "form_name",
    label: "Request Name",
    minWidth: 100,
    align: "center",
  },
  {
    id: "date_created",
    label: "Date Created",
    minWidth: 170,
    align: "center",
  },
  {
    id: "date_approved",
    label: "Date Approved",
    minWidth: 170,
    align: "center",
  },
  {
    id: "status",
    label: "Status",
    minWidth: 170,
    align: "center",
  },
  {
    id: "note",
    label: "Note",
    minWidth: 170,
    align: "center",
  },
  {
    id: "account_id",
    label: "Resquestor",
    minWidth: 170,
    align: "center",
  }
];

export const columnsApprovalList = [
  {
    id: "id",
    label: "ID",
    minWidth: 170,
    align: "center",
  },
  {
    id: "requestName",
    label: "Request Name",
    minWidth: 100,
    align: "center",
  },
  {
    id: "status",
    label: "Status",
    minWidth: 170,
    align: "center",
  },
  {
    id: "type",
    label: "Type",
    minWidth: 170,
    align: "center",
  },
  {
    id: "requestor",
    label: "Requestor",
    minWidth: 170,
    align: "center",
  },
  {
    id: "action",
    label: "Action",
    minWidth: 170,
    align: "center",
  },
];

export const rowsApprovalList = [
  {
    id: 1,
    requestName: "Xác nhận hoãn nghĩa vụ quân sự",
    status: "Waiting",
    type: "PDF",
    requestor: "ITITIU19040",
    action: "",
  },
  {
    id: 1,
    requestName: "Xác nhận hoãn nghĩa vụ quân sự",
    status: "Waiting",
    type: "PDF",
    requestor: "ITITIU19040",
    action: "",
  },
  {
    id: 1,
    requestName: "Xác nhận hoãn nghĩa vụ quân sự",
    status: "Waiting",
    type: "PDF",
    requestor: "ITITIU19040",
    action: "",
  },
  {
    id: 1,
    requestName: "Xác nhận hoãn nghĩa vụ quân sự",
    status: "Waiting",
    type: "PDF",
    requestor: "ITITIU19040",
    action: "",
  },
  {
    id: 1,
    requestName: "Xác nhận hoãn nghĩa vụ quân sự",
    status: "Waiting",
    type: "PDF",
    requestor: "ITITIU19040",
    action: "",
  },
  {
    id: 1,
    requestName: "Xác nhận hoãn nghĩa vụ quân sự",
    status: "Waiting",
    type: "PDF",
    requestor: "ITITIU19040",
    action: "",
  },
  {
    id: 1,
    requestName: "Xác nhận hoãn nghĩa vụ quân sự",
    status: "Waiting",
    type: "PDF",
    requestor: "ITITIU19040",
    action: "",
  },
  {
    id: 1,
    requestName: "Xác nhận hoãn nghĩa vụ quân sự",
    status: "Waiting",
    type: "PDF",
    requestor: "ITITIU19040",
    action: "",
  },
  {
    id: 1,
    requestName: "Xác nhận hoãn nghĩa vụ quân sự",
    status: "Waiting",
    type: "PDF",
    requestor: "ITITIU19040",
    action: "",
  },
  {
    id: 1,
    requestName: "Xác nhận hoãn nghĩa vụ quân sự",
    status: "Waiting",
    type: "PDF",
    requestor: "ITITIU19040",
    action: "",
  },
  {
    id: 1,
    requestName: "Xác nhận hoãn nghĩa vụ quân sự",
    status: "Waiting",
    type: "PDF",
    requestor: "ITITIU19040",
    action: "",
  },
];
